### ISSUE TITLE
3.3.2版本最后一步出错

### ISSUE THREAD

**Issue by yuuuuuuer** [CLOUDERHEM/legym#1]
我解开了3.3.2版本的加固，定位到了和这里相似的hs函数，正苦于找不到函数的内部实现方法，在看过这个破解过程后才了解到hs函数内部由那个so文件实现。按照你的方法使用IDA解析了so文件,但在其中只能找到一个声明hs函数的DCB指令，却找不到实现的函数在哪里。如果看到希望能与我联系。

**Comment by CLOUDERHEM** [comment]
cXE6MTQ4OTc4MDEzNywg5aSH5rOoZ2l0aHVi==
